apiVersion: v1
kind: Secret
metadata:
  name: gopay-secrets
  labels:
    {{- include "gopay.labels" . | nindent 4 }}
type: Opaque
stringData:
  ADMIN_API_KEY: {{ .Values.secret.adminApiKey | quote }}
  DB_USER: {{ .Values.secret.dbUser | quote }}
  DB_PASSWORD: {{ .Values.secret.dbPassword | quote }}
  MASTER_KEY: {{ .Values.secret.masterKey | quote }}
